language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
env:
- IS_BAMBOO=true
install:
- ./gradlew assemble
script:
- ./gradlew --no-daemon --info clean :test -PremoteDebug=false -PincludeString="**/Atlas*FastTestSuite.class" -PuseClover=false -PlogLevel=verbose -PscsDataBufferSize=8142 -PforkEveryProp=1 -PkeepScsUp=false -PshowScsWindows=false -PshowScsYoGraphics=false -PcreateVideos=false
branches:
    only:
    - feature/travis-ci-experiment